## Chapter 1

Artificial intelligence > machine learning > deep learning

Machine learning discovers rules to execute a data-processiong tasks.

Deep learning is a specific subfiend of machine learning: a new take on learning prepresentations from data that puts an emphasis on learning successive layers of increasingly meaningful representations.

How many layers contribute to a model of the data is called the depth of the model.

In deep learning, these layered representations are learnied vis models called newral networks.

You can think of a deep network as a multistage information-distillation operation, where information goes through successive filters and comes out increasingly purified.

<img src = 'deep_learning.png'>

These are the two techniques you should be the most familiar with in order to be successful in applied machine learning today: gradient boosting machines, for shallow- learning problems; and deep learning, for perceptual problems. In technical terms, this means you’ll need to be familiar with XGBoost and Keras—the two libraries that currently dominate Kaggle competitions. 

## Chapter 2

### Sample Model

In [2]:
import warnings
warnings.filterwarnings('ignore')
from keras.datasets import mnist

Using TensorFlow backend.


In [26]:
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [4]:
train_images.shape

(60000, 28, 28)

In [5]:
len(train_labels)

60000

In [6]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [7]:
test_images.shape

(10000, 28, 28)

In [8]:
len(test_labels)

10000

In [9]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [10]:
from keras import models
from keras import layers

In [11]:
network = models.Sequential()
network.add(layers.Dense(512, activation='relu', input_shape=(28*28,)))
network.add(layers.Dense(10, activation='softmax'))

The core building block of neural networks is the layer, a data-processiong module that is a filter of data. A deep learning model is a sieve made of a successio of increasingly refined data filters- the layers.

Aside from the network, we need three more things as part of the compilation step:
- loss function
- optimizer
- metrics to monitor during training and testing 

In [12]:
network.compile(optimizer = 'rmsprop',
                loss = 'categorical_crossentropy',
                metrics = ['accuracy'])

In [15]:
train_images.max()

255

In [16]:
train_images.min()

0

In [17]:
test_images.max()

255

In [18]:
test_images.min()

0

In [27]:
train_images = train_images.reshape((60000, 28*28))
train_images = train_images.astype('float32')/255
test_images = test_images.reshape((10000, 28*28))
test_images = test_images.astype('float32')/255

In [20]:
from keras.utils import to_categorical

In [28]:
# encode the labels from [1, ..., 10] to nd array 
# of binary vectors
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [29]:
train_labels

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], dtype=float32)

In [30]:
network.fit(train_images, train_labels, epochs = 5, batch_size = 128)

Epoch 1/5
60000/60000 [==============================] - 8s 134us/step - loss: 0.2521 - acc: 0.9269
Epoch 2/5
60000/60000 [==============================] - 14s 241us/step - loss: 0.1042 - acc: 0.9689
Epoch 3/5
60000/60000 [==============================] - 16s 260us/step - loss: 0.0687 - acc: 0.9797
Epoch 4/5
60000/60000 [==============================] - 10s 158us/step - loss: 0.0506 - acc: 0.9848
Epoch 5/5
60000/60000 [==============================] - 5s 87us/step - loss: 0.0377 - acc: 0.9890


In [31]:
test_loss, test_acc = network.evaluate(test_images, test_labels)

10000/10000 [==============================] - 1s 51us/step


In [32]:
print('test_acc: ', test_acc)

test_acc:  0.9781


### Data representations for neural networks

A tensor is a container for data - almost always numerical data. Tensors are a generalization of matrices to an arbitrary number of dimensions.

- A tensor that contains only one number is called a scalar. You can display the number of axes of a numpy tensor via the `ndim` attribute. A scalar tensor has 0 axes. The number of axes of a tensor is also called its `rank`.